const $=s=>document.querySelector(s), KEY='fitness_odyssey_solo_41';
const todayKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dateLabel=()=>new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'long',day:'numeric',weekday:'short'}).format(new Date());
const defaults={route:'today',profile:{name:'勇者',goal:'引體向上超過 3 下',minutes:25},xp:0,gold:0,level:1,streak:0,lastCompleted:'',today:'',completed:[],sideCompleted:[],history:[],stats:{strength:18,core:18,endurance:15,mobility:15,recovery:15},pullup:{max:1,hang:15},world:1,audio:false};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}')); state.profile={...defaults.profile,...state.profile};state.stats={...defaults.stats,...state.stats};state.pullup={...defaults.pullup,...state.pullup};
function rollover(){const t=todayKey();if(state.today!==t){state.today=t;state.completed=[];state.sideCompleted=[];save()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function pct(a,b){return Math.max(0,Math.min(100,Math.round(a/b*100)))}
const main=[{id:'warmup',name:'動態熱身',meta:'3 分鐘 · 肩胛與核心啟動',xp:20},{id:'push',name:'跪姿伏地挺身',meta:'3 組 × 15 下',xp:35},{id:'plank',name:'平板撐',meta:'3 組 × 20–25 秒',xp:35},{id:'bridge',name:'臀橋',meta:'3 組 × 15 下',xp:30},{id:'deadbug',name:'Dead Bug',meta:'3 組 × 左右各 10 下',xp:35},{id:'curl',name:'二頭彎舉',meta:'3 組 × 10 下',xp:30},{id:'hang',name:'懸垂 Hang',meta:'2 組力竭 · 目標突破 15 秒',xp:40}];
const side=[{id:'water',name:'喝水 2000 ml',xp:15},{id:'walk',name:'步行 6000 步',xp:20},{id:'protein',name:'每餐攝取蛋白質',xp:20},{id:'sleep',name:'今晚睡滿 7 小時',xp:20}];
function levelFromXP(){return Math.floor(state.xp/300)+1} function render(){rollover();state.level=levelFromXP();document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));$('#page-title').textContent={today:'今日任務',world:'冒險世界',hero:'英雄能力',journal:'訓練紀錄',settings:'設定'}[state.route];({today:renderToday,world:renderWorld,hero:renderHero,journal:renderJournal,settings:renderSettings}[state.route])()}
function quest(q,type){const done=(type==='main'?state.completed:state.sideCompleted).includes(q.id);return `<div class="quest ${done?'done':''}"><button class="quest-check" onclick="toggle('${type}','${q.id}')">${done?'✓':''}</button><div><div class="quest-name">${q.name}</div><div class="quest-meta">${q.meta||'副線任務'} · +${q.xp} XP</div></div><span class="badge">${done?'完成':'待完成'}</span></div>`}
function renderToday(){const md=state.completed.length,sd=state.sideCompleted.length,all=md===main.length,total=main.length+side.length,done=md+sd;const bossHP=Math.max(0,100-Math.round(md/main.length*100));$('#view').innerHTML=`<section class="card hero-card"><div class="row between"><div><span class="badge">Lv.${state.level}</span><h2>${state.profile.name}</h2><p class="muted">${dateLabel()} · 連續 ${state.streak} 天</p></div><div><div class="big-number">${done}/${total}</div><small class="muted">今日進度</small></div></div><div class="bar-label"><span>XP ${state.xp}</span><strong>${state.xp%300}/300</strong></div><div class="progress"><span style="width:${pct(state.xp%300,300)}%"></span></div></section><section class="card boss"><div class="row between"><div><span class="eyebrow">TODAY BOSS</span><h2>怠惰獸</h2></div><div class="boss-icon">👹</div></div><div class="bar-label"><span>HP</span><strong>${bossHP}%</strong></div><div class="progress dangerbar"><span style="width:${bossHP}%"></span></div><p class="muted">每完成一項主線，就削弱 Boss。</p></section><section class="card"><div class="row between"><h2>主線任務</h2><span class="badge">${md}/${main.length}</span></div>${main.map(q=>quest(q,'main')).join('')}</section><section class="card"><div class="row between"><h2>副線任務</h2><span class="badge">${sd}/${side.length}</span></div>${side.map(q=>quest(q,'side')).join('')}</section>${all?`<section class="card reward"><h2>🔥 今日主線完成</h2><p>你已擊敗怠惰獸。副線可繼續完成，不影響今日連續紀錄。</p><button class="btn full" onclick="tomorrowPreview()">查看明日挑戰</button></section>`:''}`}
window.toggle=(type,id)=>{const list=type==='main'?state.completed:state.sideCompleted, q=(type==='main'?main:side).find(x=>x.id===id),i=list.indexOf(id);if(i>=0){list.splice(i,1);state.xp=Math.max(0,state.xp-q.xp)}else{list.push(id);state.xp+=q.xp;state.gold+=Math.ceil(q.xp/2);if(id==='push'||id==='curl')state.stats.strength++;if(id==='plank'||id==='deadbug')state.stats.core++;if(id==='hang'){state.stats.strength++;state.stats.endurance++}}const completedAll=main.every(x=>state.completed.includes(x));if(completedAll&&state.lastCompleted!==state.today){const yesterday=new Date(Date.now()-86400000);const y=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(yesterday);state.streak=state.lastCompleted===y?state.streak+1:1;state.lastCompleted=state.today;state.xp+=100;state.gold+=80;state.history.push({date:state.today,title:'主線完成',detail:`完成 ${main.length} 項訓練，獲得完成獎勵 +100 XP`});if(state.streak%7===0)state.world=Math.min(5,state.world+1)}save();render()};
window.tomorrowPreview=()=>{show(`<h2>明日挑戰預覽</h2><div class="story"><strong>重點：引體向上基礎</strong><br>肩胛下壓、負向引體、核心抗伸展與懸垂。系統會在明天自動建立新任務，不會提前算入今日。</div>`)};
function renderWorld(){const maps=[['新手村','🌿'],['暗影森林','🌲'],['熔岩峽谷','🌋'],['冰封山脈','🏔️'],['魔王城','🏰']];$('#view').innerHTML=`<section class="card"><h2>冒險地圖</h2><p class="muted">每連續完成 7 天，解鎖下一個區域。</p><div class="world">${maps.map((m,i)=>`<div class="world-node ${i<state.world?'unlocked':'locked'}"><div class="row between"><strong>${m[1]} ${m[0]}</strong><span>${i<state.world?'已解鎖':'🔒'}</span></div><small class="muted">${i===0?'建立穩定運動習慣':`需要 ${i*7} 天里程碑`}</small></div>`).join('')}</div></section>`}
function renderHero(){const stats=[['力量',state.stats.strength],['核心',state.stats.core],['耐力',state.stats.endurance],['活動度',state.stats.mobility],['恢復',state.stats.recovery]];$('#view').innerHTML=`<section class="card hero-card"><div class="row between"><div><span class="badge">Lv.${state.level}</span><h2>${state.profile.name}</h2><p class="muted">目標：${state.profile.goal}</p></div><div class="big-number">${state.gold}</div></div><small class="muted">Gold</small></section><section class="card"><h2>引體向上養成</h2><div class="grid"><div class="stat"><span>目前最大值</span><strong>${state.pullup.max} 下</strong></div><div class="stat"><span>懸垂紀錄</span><strong>${state.pullup.hang} 秒</strong></div></div><div class="bar-label"><span>目標 3 下</span><strong>${pct(state.pullup.max,3)}%</strong></div><div class="progress"><span style="width:${pct(state.pullup.max,3)}%"></span></div><button class="btn secondary full mt" onclick="updatePullup()">更新測試紀錄</button></section><section class="card"><h2>能力值</h2>${stats.map(s=>`<div class="bar-label"><span>${s[0]}</span><strong>${s[1]}</strong></div><div class="progress"><span style="width:${s[1]}%"></span></div>`).join('')}</section>`}
window.updatePullup=()=>show(`<h2>更新引體向上紀錄</h2><label><span>最大完整引體向上</span><input id="pull" type="number" min="0" value="${state.pullup.max}"></label><label><span>最長懸垂秒數</span><input id="hang" type="number" min="0" value="${state.pullup.hang}"></label><button class="btn full" onclick="savePullup()">儲存</button>`);window.savePullup=()=>{state.pullup.max=+$('#pull').value;state.pullup.hang=+$('#hang').value;save();$('#modal').close();render()};
function renderJournal(){$('#view').innerHTML=`<section class="card"><div class="row between"><h2>訓練紀錄</h2><span class="badge">${state.history.length} 筆</span></div>${state.history.length?state.history.slice().reverse().map(h=>`<div class="lesson"><strong>${h.title}</strong><div class="muted">${h.date} · ${h.detail}</div></div>`).join(''):'<p class="muted">完成第一天主線後，紀錄會出現在這裡。</p>'}</section>`}
function renderSettings(){$('#view').innerHTML=`<section class="card"><h2>英雄設定</h2><label><span>名稱</span><input id="name" type="text" value="${state.profile.name}"></label><label><span>主要目標</span><input id="goal" type="text" value="${state.profile.goal}"></label><button class="btn full" onclick="saveSettings()">儲存設定</button></section><section class="card"><h2>資料管理</h2><div class="grid"><button class="btn secondary" onclick="exportData()">匯出紀錄</button><button class="btn danger" onclick="resetData()">重設資料</button></div></section><section class="card"><h2>版本</h2><p class="muted">V7.0 Solo Build 4.1 · 台北時區日期修正 · 本機永久儲存 · PWA</p></section>`}
window.saveSettings=()=>{state.profile.name=$('#name').value.trim()||'勇者';state.profile.goal=$('#goal').value.trim()||defaults.profile.goal;save();render()};window.exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='fitness-odyssey-solo-save.json';a.click()};window.resetData=()=>{if(confirm('確定清除所有進度？')){localStorage.removeItem(KEY);location.reload()}};
function show(html){$('#modal-content').innerHTML=html;$('#modal').showModal()}$('#modal-close').onclick=()=>$('#modal').close();document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;save();render()});
$('#audio-btn').onclick=()=>{state.audio=!state.audio;$('#audio-btn').textContent=state.audio?'🔊':'🔇';save()};$('#audio-btn').textContent=state.audio?'🔊':'🔇';let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#install-btn').classList.remove('hidden')});$('#install-btn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};rollover();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
