const $=s=>document.querySelector(s);
const KEY='fitness_odyssey_solo_50', OLD_KEY='fitness_odyssey_solo_41';
const TAIPEI='Asia/Taipei';
const todayKey=(date=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:TAIPEI,year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
const dateLabel=()=>new Intl.DateTimeFormat('zh-TW',{timeZone:TAIPEI,month:'long',day:'numeric',weekday:'short'}).format(new Date());
const defaults={route:'today',profile:{name:'勇者',goal:'引體向上超過 3 下',minutes:25},xp:0,gold:0,level:1,streak:0,lastCompleted:'',today:'',completed:[],sideCompleted:[],customSide:[],history:[],dailyRecords:{},claimedAchievements:[],stats:{strength:18,core:18,endurance:15,mobility:15,recovery:15},pullup:{max:1,hang:15},world:1,audio:false};
const stored=localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||'{}';
let state={...defaults,...JSON.parse(stored)};
state.profile={...defaults.profile,...state.profile};state.stats={...defaults.stats,...state.stats};state.pullup={...defaults.pullup,...state.pullup};
state.customSide=Array.isArray(state.customSide)?state.customSide:[];state.dailyRecords=state.dailyRecords||{};state.claimedAchievements=state.claimedAchievements||[];
const main=[
{id:'warmup',name:'動態熱身',meta:'3 分鐘 · 肩胛與核心啟動',xp:20,timer:180},
{id:'push',name:'跪姿伏地挺身',meta:'3 組 × 15 下',xp:35,timer:45},
{id:'plank',name:'平板撐',meta:'3 組 × 20–25 秒',xp:35,timer:25},
{id:'bridge',name:'臀橋',meta:'3 組 × 15 下',xp:30,timer:45},
{id:'deadbug',name:'Dead Bug',meta:'3 組 × 左右各 10 下',xp:35,timer:60},
{id:'curl',name:'二頭彎舉',meta:'3 組 × 10 下',xp:30,timer:45},
{id:'hang',name:'懸垂 Hang',meta:'2 組力竭 · 目標突破 15 秒',xp:40,timer:15}
];
const baseSide=[{id:'water',name:'喝水 2000 ml',xp:15},{id:'walk',name:'步行 6000 步',xp:20},{id:'protein',name:'每餐攝取蛋白質',xp:20},{id:'sleep',name:'今晚睡滿 7 小時',xp:20}];
const achievements=[
{id:'first',icon:'🏁',name:'踏上旅程',desc:'完成第一次主線',test:()=>completedDays()>=1},
{id:'streak3',icon:'🔥',name:'三日不斷',desc:'連續完成 3 天',test:()=>state.streak>=3},
{id:'streak7',icon:'👑',name:'一週勇者',desc:'連續完成 7 天',test:()=>state.streak>=7},
{id:'pull3',icon:'🦅',name:'突破地心引力',desc:'完成 3 下引體向上',test:()=>state.pullup.max>=3},
{id:'hang30',icon:'⏱️',name:'鋼鐵之握',desc:'懸垂達到 30 秒',test:()=>state.pullup.hang>=30}
];
let timer=null,timerLeft=0,audioCtx=null,musicTimer=null;
function allSide(){return [...baseSide,...state.customSide]}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function pct(a,b){return Math.max(0,Math.min(100,Math.round((a/b)*100)||0))}
function dayBefore(key){const d=new Date(`${key}T12:00:00+08:00`);d.setDate(d.getDate()-1);return todayKey(d)}
function rollover(){const t=todayKey();if(state.today!==t){state.today=t;state.completed=[];state.sideCompleted=[];save()}}
function levelFromXP(){return Math.floor(state.xp/300)+1}
function completedDays(){return Object.values(state.dailyRecords).filter(x=>x.mainComplete).length}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1800)}
function tone(freq=520,duration=.12,type='sine'){if(!state.audio)return;audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.055,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}
function checkAchievements(){achievements.forEach(a=>{if(a.test()&&!state.claimedAchievements.includes(a.id)){state.claimedAchievements.push(a.id);state.gold+=100;state.xp+=50;toast(`成就解鎖：${a.name}`);tone(880,.25,'triangle')}})}
function render(){rollover();state.level=levelFromXP();document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));$('#page-title').textContent={today:'今日任務',world:'冒險世界',hero:'英雄能力',journal:'訓練紀錄',settings:'設定'}[state.route];({today:renderToday,world:renderWorld,hero:renderHero,journal:renderJournal,settings:renderSettings}[state.route])();save()}
function quest(q,type){const done=(type==='main'?state.completed:state.sideCompleted).includes(q.id);return `<div class="quest ${done?'done':''}"><button class="quest-check" onclick="toggleQuest('${type}','${q.id}')">${done?'✓':''}</button><div><div class="quest-name">${escapeHtml(q.name)}</div><div class="quest-meta">${escapeHtml(q.meta||'副線任務')} · +${q.xp} XP</div></div><div class="quest-action">${q.timer?`<button class="mini-btn" onclick="openTimer(${q.timer},'${escapeAttr(q.name)}')">⏱</button>`:''}${type==='side'&&q.custom?`<button class="mini-btn" onclick="deleteSide('${q.id}')">✕</button>`:`<span class="badge">${done?'完成':'待完成'}</span>`}</div></div>`}
function renderToday(){const sides=allSide(),md=state.completed.length,sd=state.sideCompleted.length,all=md===main.length,total=main.length+sides.length,done=md+sd,bossHP=Math.max(0,100-Math.round(md/main.length*100));$('#view').innerHTML=`<section class="card hero-card"><div class="row between"><div><span class="badge">Lv.${state.level}</span><h2>${escapeHtml(state.profile.name)}</h2><p class="muted">${dateLabel()} · 連續 ${state.streak} 天</p></div><div><div class="big-number">${done}/${total}</div><small class="muted">今日進度</small></div></div><div class="bar-label"><span>XP ${state.xp}</span><strong>${state.xp%300}/300</strong></div><div class="progress"><span style="width:${pct(state.xp%300,300)}%"></span></div></section><section class="card boss"><div class="row between"><div><span class="eyebrow">TODAY BOSS</span><h2>${all?'已擊敗怠惰獸':'怠惰獸'}</h2></div><div class="boss-icon">${all?'🏆':'👹'}</div></div><div class="bar-label"><span>HP</span><strong>${bossHP}%</strong></div><div class="progress dangerbar"><span style="width:${bossHP}%"></span></div><p class="muted">每完成一項主線，就削弱 Boss。</p></section><section class="card"><div class="row between"><h2>主線任務</h2><span class="badge">${md}/${main.length}</span></div>${main.map(q=>quest(q,'main')).join('')}</section><section class="card"><div class="row between"><h2>副線任務</h2><button class="mini-btn" onclick="addSide()">＋新增</button></div>${sides.map(q=>quest(q,'side')).join('')}</section>${all?`<section class="card reward"><h2>🔥 今日主線完成</h2><p>你已擊敗怠惰獸，獲得完成獎勵。現在可挑戰副線或查看明日任務。</p><button class="btn full" onclick="tomorrowPreview()">查看明日挑戰</button></section>`:''}`}
window.toggleQuest=(type,id)=>{const pool=type==='main'?main:allSide(),list=type==='main'?state.completed:state.sideCompleted,q=pool.find(x=>x.id===id);if(!q)return;const wasLevel=levelFromXP(),i=list.indexOf(id);if(i>=0){list.splice(i,1);state.xp=Math.max(0,state.xp-q.xp);state.gold=Math.max(0,state.gold-Math.ceil(q.xp/2));tone(220,.08)}else{list.push(id);state.xp+=q.xp;state.gold+=Math.ceil(q.xp/2);tone(620,.1,'triangle');if(id==='push'||id==='curl')state.stats.strength++;if(id==='plank'||id==='deadbug')state.stats.core++;if(id==='hang'){state.stats.strength++;state.stats.endurance++}}
const allMain=main.every(x=>state.completed.includes(x));const record=state.dailyRecords[state.today]||{};
if(allMain&&!record.mainComplete){const y=dayBefore(state.today);state.streak=state.dailyRecords[y]?.mainComplete?(state.dailyRecords[y].streak||state.streak)+1:1;state.lastCompleted=state.today;state.xp+=100;state.gold+=80;state.dailyRecords[state.today]={...record,mainComplete:true,streak:state.streak};state.history.push({date:state.today,title:'主線完成',detail:`完成 ${main.length} 項訓練，獲得 +100 XP、+80 Gold`});if(state.streak%7===0)state.world=Math.min(5,state.world+1);tone(980,.3,'triangle');toast('Boss 擊敗！完成獎勵已發放')}
if(!allMain&&record.mainComplete){state.dailyRecords[state.today]={...record,mainComplete:false};state.xp=Math.max(0,state.xp-100);state.gold=Math.max(0,state.gold-80);state.history=state.history.filter(h=>!(h.date===state.today&&h.title==='主線完成'));state.streak=state.dailyRecords[dayBefore(state.today)]?.streak||0;state.lastCompleted=state.streak?dayBefore(state.today):''}
checkAchievements();save();const newLevel=levelFromXP();render();if(newLevel>wasLevel)show(`<div style="text-align:center"><div class="boss-icon">✨</div><h2>升級！Lv.${newLevel}</h2><p class="muted">你的訓練累積正在轉化為真正的能力。</p></div>`)};
window.addSide=()=>show(`<h2>新增副線任務</h2><label><span>任務名稱</span><input id="side-name" maxlength="30" placeholder="例如：伸展 10 分鐘"></label><label><span>XP 獎勵</span><select id="side-xp"><option value="10">10 XP</option><option value="15" selected>15 XP</option><option value="20">20 XP</option><option value="25">25 XP</option></select></label><button class="btn full" onclick="saveSide()">加入今日副線</button>`);
window.saveSide=()=>{const name=$('#side-name').value.trim();if(!name)return toast('請輸入任務名稱');state.customSide.push({id:`custom_${Date.now()}`,name,xp:+$('#side-xp').value,custom:true});save();$('#modal').close();render()};
window.deleteSide=id=>{state.customSide=state.customSide.filter(x=>x.id!==id);state.sideCompleted=state.sideCompleted.filter(x=>x!==id);save();render()};
window.tomorrowPreview=()=>show(`<h2>明日挑戰預覽</h2><div class="story"><strong>重點：引體向上基礎</strong><br>肩胛下壓、負向引體、核心抗伸展與懸垂。系統會在明天自動重置今日勾選，不會提前計入。</div>`);
window.openTimer=(seconds,title)=>{timerLeft=seconds;show(`<h2>${escapeHtml(title)} 計時</h2><div id="timer-display" class="timer-display">${formatTime(timerLeft)}</div><div class="timer-presets"><button class="btn secondary" onclick="setTimer(15)">15秒</button><button class="btn secondary" onclick="setTimer(25)">25秒</button><button class="btn secondary" onclick="setTimer(45)">45秒</button><button class="btn secondary" onclick="setTimer(60)">60秒</button></div><button id="timer-toggle" class="btn full mt" onclick="toggleTimer()">開始</button>`)};
window.setTimer=s=>{clearInterval(timer);timer=null;timerLeft=s;$('#timer-display').textContent=formatTime(s);$('#timer-toggle').textContent='開始'};
window.toggleTimer=()=>{if(timer){clearInterval(timer);timer=null;$('#timer-toggle').textContent='繼續';return}tone(500,.08);$('#timer-toggle').textContent='暫停';timer=setInterval(()=>{timerLeft--;const el=$('#timer-display');if(el)el.textContent=formatTime(timerLeft);if(timerLeft<=0){clearInterval(timer);timer=null;tone(900,.5,'square');toast('計時完成！');if($('#timer-toggle'))$('#timer-toggle').textContent='完成'}},1000)};
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.max(0,s%60)).padStart(2,'0')}`}
function renderWorld(){const maps=[['新手村','🌿'],['暗影森林','🌲'],['熔岩峽谷','🌋'],['冰封山脈','🏔️'],['魔王城','🏰']];$('#view').innerHTML=`<section class="card"><h2>冒險地圖</h2><p class="muted">每連續完成 7 天，解鎖下一個區域。</p><div class="world">${maps.map((m,i)=>`<div class="world-node ${i<state.world?'unlocked':'locked'}"><div class="row between"><strong>${m[1]} ${m[0]}</strong><span>${i<state.world?'已解鎖':'🔒'}</span></div><small class="muted">${i===0?'建立穩定運動習慣':`需要 ${i*7} 天里程碑`}</small></div>`).join('')}</div></section><section class="card"><h2>成就殿堂</h2>${achievements.map(a=>`<div class="achievement ${state.claimedAchievements.includes(a.id)?'':'locked'}"><div class="icon">${a.icon}</div><div><strong>${a.name}</strong><div class="muted">${a.desc}${state.claimedAchievements.includes(a.id)?' · 已解鎖':' · 未解鎖'}</div></div></div>`).join('')}</section>`}
function renderHero(){const stats=[['力量',state.stats.strength],['核心',state.stats.core],['耐力',state.stats.endurance],['活動度',state.stats.mobility],['恢復',state.stats.recovery]];$('#view').innerHTML=`<section class="card hero-card"><div class="row between"><div><span class="badge">Lv.${state.level}</span><h2>${escapeHtml(state.profile.name)}</h2><p class="muted">目標：${escapeHtml(state.profile.goal)}</p></div><div class="big-number">${state.gold}</div></div><small class="muted">Gold</small></section><section class="card"><h2>引體向上養成</h2><div class="grid"><div class="stat"><span>目前最大值</span><strong>${state.pullup.max} 下</strong></div><div class="stat"><span>懸垂紀錄</span><strong>${state.pullup.hang} 秒</strong></div></div><div class="bar-label"><span>目標 3 下</span><strong>${pct(state.pullup.max,3)}%</strong></div><div class="progress"><span style="width:${pct(state.pullup.max,3)}%"></span></div><button class="btn secondary full mt" onclick="updatePullup()">更新測試紀錄</button></section><section class="card"><h2>能力值</h2>${stats.map(s=>`<div class="bar-label"><span>${s[0]}</span><strong>${s[1]}</strong></div><div class="progress"><span style="width:${Math.min(s[1],100)}%"></span></div>`).join('')}</section>`}
window.updatePullup=()=>show(`<h2>更新引體向上紀錄</h2><label><span>最大完整引體向上</span><input id="pull" type="number" min="0" value="${state.pullup.max}"></label><label><span>最長懸垂秒數</span><input id="hang" type="number" min="0" value="${state.pullup.hang}"></label><button class="btn full" onclick="savePullup()">儲存</button>`);
window.savePullup=()=>{state.pullup.max=Math.max(0,+$('#pull').value||0);state.pullup.hang=Math.max(0,+$('#hang').value||0);checkAchievements();save();$('#modal').close();render()};
function last14(){const arr=[];for(let i=13;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=todayKey(d);arr.push({key,label:new Intl.DateTimeFormat('zh-TW',{timeZone:TAIPEI,day:'numeric'}).format(d),weekday:new Intl.DateTimeFormat('zh-TW',{timeZone:TAIPEI,weekday:'narrow'}).format(d)})}return arr}
function renderJournal(){const days=last14();$('#view').innerHTML=`<section class="card"><div class="row between"><h2>14 日行事曆</h2><span class="badge">完成 ${completedDays()} 天</span></div><div class="calendar">${days.map(d=>`<div class="day ${state.dailyRecords[d.key]?.mainComplete?'done':''} ${d.key===state.today?'today':''}"><span>${d.weekday}</span><strong>${d.label}</strong>${state.dailyRecords[d.key]?.mainComplete?'<span>✓</span>':''}</div>`).join('')}</div></section><section class="card"><div class="row between"><h2>訓練紀錄</h2><span class="badge">${state.history.length} 筆</span></div>${state.history.length?state.history.slice().reverse().map(h=>`<div class="lesson"><strong>${escapeHtml(h.title)}</strong><div class="muted">${h.date} · ${escapeHtml(h.detail)}</div></div>`).join(''):'<p class="muted">完成第一天主線後，紀錄會出現在這裡。</p>'}</section>`}
function renderSettings(){$('#view').innerHTML=`<section class="card"><h2>英雄設定</h2><label><span>名稱</span><input id="name" type="text" value="${escapeAttr(state.profile.name)}"></label><label><span>主要目標</span><input id="goal" type="text" value="${escapeAttr(state.profile.goal)}"></label><button class="btn full" onclick="saveSettings()">儲存設定</button></section><section class="card"><h2>聲音</h2><p class="muted">使用內建合成音效，不需要網路或額外音樂檔。</p><button class="btn secondary full" onclick="toggleMusic()">${musicTimer?'停止背景節奏':'播放背景節奏'}</button></section><section class="card"><h2>資料管理</h2><div class="grid"><button class="btn secondary" onclick="exportData()">匯出紀錄</button><button class="btn danger" onclick="resetData()">重設資料</button></div></section><section class="card"><h2>版本</h2><p class="muted">V7.0 Solo Build 5.0 · 升級動畫 · 自訂副線 · 訓練計時器 · 14 日行事曆 · 成就 · 內建音效 · PWA</p></section>`}
window.saveSettings=()=>{state.profile.name=$('#name').value.trim()||'勇者';state.profile.goal=$('#goal').value.trim()||defaults.profile.goal;save();render()};
window.toggleMusic=()=>{state.audio=true;$('#audio-btn').textContent='🔊';if(musicTimer){clearInterval(musicTimer);musicTimer=null;toast('背景節奏已停止')}else{let i=0;const notes=[220,277,330,277];tone(notes[i++%4],.15,'triangle');musicTimer=setInterval(()=>tone(notes[i++%4],.15,'triangle'),700);toast('背景節奏已開始')}save();render()};
window.exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='fitness-odyssey-solo-build-5-save.json';a.click();URL.revokeObjectURL(a.href)};
window.resetData=()=>{if(confirm('確定清除所有進度？')){localStorage.removeItem(KEY);localStorage.removeItem(OLD_KEY);location.reload()}};
function show(html){clearInterval(timer);timer=null;$('#modal-content').innerHTML=html;$('#modal').showModal()}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(v=''){return escapeHtml(v)}
$('#modal-close').onclick=()=>{clearInterval(timer);timer=null;$('#modal').close()};
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;render()});
$('#audio-btn').onclick=()=>{state.audio=!state.audio;$('#audio-btn').textContent=state.audio?'🔊':'🔇';if(!state.audio&&musicTimer){clearInterval(musicTimer);musicTimer=null}save();tone(600,.1)};
$('#audio-btn').textContent=state.audio?'🔊':'🔇';
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#install-btn').classList.remove('hidden')});
$('#install-btn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#install-btn').classList.add('hidden')}};
rollover();checkAchievements();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
